name: Mirror

on:
  push:
    branches:
      - main

env:
  MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Config Git
        run: |
          git config --global user.email "sumneko@hotmail.com"
          git config --global user.name "最萌小汐（宇宙创生）"

      - name: Checkout Mirror
        uses: actions/checkout@v4
        with:
          repository: 'CliCli-Editor/y3-lualib'
          token: $MIRROR_TOKEN
          ref: main

      - name: Mirror
        run: |
          git remote add source "https://github.com/y3-editor/y3-lualib.git"
          git checkout source
          git push --mirror main
