name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Mirror
        env:
          TARGET_REPO: ${{ secrets.MIRROR_TARGET_REPO }}  # 目标仓库的 URL
          TARGET_TOKEN: ${{ secrets.MIRROR_TARGET_TOKEN }}  # 目标仓库的访问权限 token
        run: |
          git remote add mirror ${{ secrets.MIRROR_TARGET_TOKEN }}@${{ secrets.MIRROR_TARGET_REPO }}
          git push --mirror mirror
