name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Config Git
        run: |
          git config --global user.email "sumneko@hotmail.com"
          git config --global user.name "最萌小汐（宇宙创生）"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror
        run: |
          git remote add --mirror=push mirror https://github.com/CliCli-Editor/y3-lualib
          git push --mirror https://oauth2:${{ secrets.MIRROR_TOKEN }}@github.com/CliCli-Editor/y3-lualib
