name: Mirror

on:
  push:
    branches:
      - main

env:
  MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Check
        run: |
          curl -H "Authorization: token $MIRROR_TOKEN" https://api.github.com/repos/CliCli-Editor/y3-lualib

      - name: Mirror
        run: |
          git config --global user.email "sumneko@hotmail.com"
          git config --global user.name "最萌小汐（宇宙创生）"
          git remote add mirror "https://oauth2:${MIRROR_TOKEN}@github.com/CliCli-Editor/y3-lualib.git"
          git push --mirror mirror
